import type { Cruise, CruiseLine, Destination, Port, Ship } from "./types";

const line = (id: string, name: string, description: string): CruiseLine => ({ id, name, description });
const destination = (id: string, name: string, region: string, description: string): Destination => ({ id, name, region, description });
const port = (id: string, name: string, country: string): Port => ({ id, name, country });

export const cruiseLines: CruiseLine[] = [
  line("princess", "Princess Cruises", "Thoughtful itineraries and effortless discovery."), line("celebrity", "Celebrity Cruises", "Modern luxury at sea."), line("holland", "Holland America Line", "Classic service, curious routes."), line("royal", "Royal Caribbean", "Big energy and family adventure."), line("norwegian", "Norwegian Cruise Line", "The freedom to cruise your way."), line("viking", "Viking", "Immersive journeys, beautifully considered."), line("seabourn", "Seabourn", "Intimate, all-inclusive luxury."), line("carnival", "Carnival Cruise Line", "Celebration for every generation.")
];
export const destinations: Destination[] = [
  destination("alaska", "Alaska", "North America", "Glaciers, quiet fjords, and wild horizons."), destination("caribbean", "Caribbean", "Tropical", "Island time, warm water, and bright nights."), destination("mediterranean", "Mediterranean", "Europe", "Ancient cities and long blue afternoons."), destination("bahamas", "Bahamas", "Tropical", "Clear water close to home."), destination("europe", "Europe", "Europe", "A grand tour by sea."), destination("hawaii", "Hawaii", "Pacific", "Volcanic landscapes and aloha spirit."), destination("mexico", "Mexico", "North America", "Color, coastlines, and living history.")
];
export const ports: Port[] = [
  port("seattle", "Seattle", "United States"), port("vancouver", "Vancouver", "Canada"), port("miami", "Miami", "United States"), port("fort-lauderdale", "Fort Lauderdale", "United States"), port("new-york", "New York", "United States"), port("rome", "Rome", "Italy"), port("barcelona", "Barcelona", "Spain"), port("athens", "Athens", "Greece"), port("honolulu", "Honolulu", "United States"), port("los-angeles", "Los Angeles", "United States"), port("san-juan", "San Juan", "Puerto Rico")
];
export const ships: Ship[] = [
  { id: "discovery", name: "Discovery Princess", lineId: "princess", capacity: 3660, built: 2022, highlights: ["Theater under the stars", "360° promenade", "Al fresco dining"] },
  { id: "edge", name: "Celebrity Edge", lineId: "celebrity", capacity: 2918, built: 2018, highlights: ["The Magic Carpet", "Rooftop garden", "Michelin-inspired dining"] },
  { id: "koningsdam", name: "Koningsdam", lineId: "holland", capacity: 2650, built: 2016, highlights: ["Music Walk", "Culinary Arts Center", "Panorama deck"] },
  { id: "icon", name: "Icon of the Seas", lineId: "royal", capacity: 5610, built: 2024, highlights: ["Category 6 waterpark", "AquaDome", "Seven pools"] },
  { id: "prima", name: "Norwegian Prima", lineId: "norwegian", capacity: 3215, built: 2022, highlights: ["Ocean Boulevard", "Infinity beach", "Indulge food hall"] },
  { id: "mars", name: "Viking Mars", lineId: "viking", capacity: 930, built: 2022, highlights: ["Nordic spa", "Included excursions", "Explorers lounge"] },
  { id: "venture", name: "Seabourn Venture", lineId: "seabourn", capacity: 264, built: 2022, highlights: ["Zodiac adventures", "Submersibles", "Open bridge"] },
  { id: "jubilee", name: "Carnival Jubilee", lineId: "carnival", capacity: 5374, built: 2023, highlights: ["Bolt coaster", "Central Park", "Family entertainment"] }
];

const images = ["/images/hero-cruise.png", "/images/caribbean-cruise.png"];
const stop = (day: number, portName: string, country: string, description: string) => ({ day, port: portName, country, description });
const cabinSet = (base: number) => [
  { type: "Interior" as const, from: base, description: "A calm, comfortable base for days out exploring.", features: ["165 sq ft", "Queen bed", "Room service"] },
  { type: "Oceanview" as const, from: base + 160, description: "Wake up to a new horizon each morning.", features: ["200 sq ft", "Picture window", "Room service"] },
  { type: "Balcony" as const, from: base + 360, description: "Your own private perch above the water.", features: ["230 sq ft", "Private balcony", "Priority boarding"] },
  { type: "Suite" as const, from: base + 970, description: "More room, more quiet, more ways to settle in.", features: ["460 sq ft", "Separate lounge", "Suite services"] }
];
const makeCruise = (id: string, title: string, lineId: string, shipId: string, destinationId: string, portId: string, departureDate: string, nights: number, base: number, cruiseType: Cruise["cruiseType"], portsList: ReturnType<typeof stop>[], featured = false, deal = true): Cruise => {
  const l = cruiseLines.find((item) => item.id === lineId)!; const s = ships.find((item) => item.id === shipId)!; const d = destinations.find((item) => item.id === destinationId)!; const p = ports.find((item) => item.id === portId)!;
  const returnDate = new Date(new Date(departureDate).getTime() + nights * 86400000).toISOString().slice(0, 10);
  return { id, slug: id, title, cruiseLine: l, ship: s, destination: d, departurePort: p, returnPort: p, departureDate, returnDate, nights, ports: portsList, images, originalPrice: base + 340, currentPrice: base, savingsPercent: Math.round((340 / (base + 340)) * 100), cabins: cabinSet(base), amenities: ["Wi-Fi packages", "Pools", "Live entertainment", "Fitness center"], description: `A considered ${nights}-night journey through ${d.name}, pairing thoughtful onboard time with the places that make this route unforgettable.`, cruiseType, featured, deal, returnToSamePort: true };
};

export const cruises: Cruise[] = [
  makeCruise("alaska-inside-passage-7-night", "7-Night Alaska Inside Passage", "princess", "discovery", "alaska", "seattle", "2027-05-04", 7, 589, "Ocean", [stop(1, "Seattle", "United States", "Set sail beneath the Olympic Mountains."), stop(2, "At Sea", "Pacific Ocean", "A day to find your favorite corner of the ship."), stop(3, "Juneau", "Alaska", "Whale watching and Mendenhall Glacier."), stop(4, "Skagway", "Alaska", "Gold rush history at the edge of the wild."), stop(5, "Glacier Bay", "Alaska", "A front-row view of ancient ice."), stop(6, "Ketchikan", "Alaska", "Totem poles, rainforest, and fresh crab."), stop(7, "Victoria", "Canada", "A late-evening walk through the Inner Harbour."), stop(8, "Seattle", "United States", "Return with a new sense of scale.")], true, true),
  makeCruise("caribbean-souls-7-night", "Eastern Caribbean & Perfect Day", "royal", "icon", "caribbean", "miami", "2027-02-14", 7, 799, "Ocean", [stop(1, "Miami", "United States", "Welcome aboard."), stop(3, "St. Thomas", "U.S. Virgin Islands", "Blue water and hillside towns."), stop(4, "St. Maarten", "Sint Maarten", "French flavor, Dutch energy."), stop(6, "Perfect Day", "Bahamas", "A private island day."), stop(8, "Miami", "United States", "Sail home with the sun still up.")], true, true),
  makeCruise("mediterranean-blue-10-night", "10-Night Mediterranean Blue", "celebrity", "edge", "mediterranean", "rome", "2027-06-12", 10, 1299, "Luxury", [stop(1, "Rome", "Italy", "Ancient streets and aperitivo."), stop(3, "Santorini", "Greece", "Whitewashed villages above the caldera."), stop(4, "Mykonos", "Greece", "Windmills, water, and late lunches."), stop(6, "Naples", "Italy", "Pompeii and perfect pizza."), stop(8, "Palma", "Spain", "A slower side of Mallorca."), stop(11, "Barcelona", "Spain", "End with Gaudí and the sea.")], true, true),
  makeCruise("alaska-glacier-discovery", "7-Night Glacier Discovery", "holland", "koningsdam", "alaska", "vancouver", "2027-05-21", 7, 749, "Ocean", [stop(1, "Vancouver", "Canada", "A beautiful Pacific departure."), stop(3, "Juneau", "Alaska", "Glacier country."), stop(4, "Sitka", "Alaska", "Forest, sea, and Tlingit culture."), stop(6, "Ketchikan", "Alaska", "The salmon capital."), stop(8, "Vancouver", "Canada", "Back to the city lights.")], false, true),
  makeCruise("bahamas-sun-weekend", "4-Night Bahamas Sun Weekend", "carnival", "jubilee", "bahamas", "fort-lauderdale", "2027-01-29", 4, 399, "Ocean", [stop(1, "Fort Lauderdale", "United States", "Start with a warm breeze."), stop(2, "At Sea", "Atlantic Ocean", "Pool deck, open sky."), stop(3, "Bimini", "Bahamas", "A bright island pause."), stop(5, "Fort Lauderdale", "United States", "A long weekend, well spent.")], false, true),
  makeCruise("hawaii-four-islands", "10-Night Hawaiian Islands", "princess", "discovery", "hawaii", "honolulu", "2027-09-04", 10, 1099, "Ocean", [stop(1, "Honolulu", "United States", "Begin in Waikīkī."), stop(3, "Maui", "United States", "Roads to Hana and golden beaches."), stop(5, "Kona", "United States", "Coffee country and manta rays."), stop(6, "Hilo", "United States", "Rainforests and waterfalls."), stop(8, "Nawiliwili", "United States", "The green cliffs of Kauai."), stop(11, "Honolulu", "United States", "The circle is complete.")], false, true),
  makeCruise("mexico-riviera-5-night", "5-Night Mexican Riviera", "norwegian", "prima", "mexico", "los-angeles", "2027-03-15", 5, 549, "Ocean", [stop(1, "Los Angeles", "United States", "Set sail from the West Coast."), stop(3, "Cabo San Lucas", "Mexico", "Landscapes carved by sun and sea."), stop(4, "Mazatlán", "Mexico", "Old town color and fresh seafood."), stop(6, "Los Angeles", "United States", "Return refreshed.")], false, true),
  makeCruise("europe-northern-lights", "12-Night Northern Europe", "viking", "mars", "europe", "barcelona", "2027-08-02", 12, 2299, "Ocean", [stop(1, "Barcelona", "Spain", "A Mediterranean beginning."), stop(4, "Lisbon", "Portugal", "Tiles, hills, and bright Atlantic light."), stop(7, "Dublin", "Ireland", "Stories in every pub."), stop(10, "Edinburgh", "United Kingdom", "Stone, sea, and a little mist."), stop(13, "Bergen", "Norway", "A gateway to the fjords.")], false, true),
  makeCruise("caribbean-southern-sail", "9-Night Southern Caribbean", "seabourn", "venture", "caribbean", "san-juan", "2027-11-08", 9, 1899, "Expedition", [stop(1, "San Juan", "Puerto Rico", "Old city, new journey."), stop(3, "St. Lucia", "Saint Lucia", "The Pitons rise from the sea."), stop(5, "Barbados", "Barbados", "Rum, rhythm, and reef."), stop(8, "Grenada", "Grenada", "Spice island in full bloom."), stop(10, "San Juan", "Puerto Rico", "The perfect final morning.")], false, true),
  makeCruise("mediterranean-classic", "7-Night Mediterranean Classic", "celebrity", "edge", "mediterranean", "barcelona", "2027-04-19", 7, 999, "Luxury", [stop(1, "Barcelona", "Spain", "A city of bold ideas."), stop(3, "Marseille", "France", "Markets and the Calanques."), stop(4, "Florence", "Italy", "Art, food, and Tuscan light."), stop(6, "Rome", "Italy", "History in every direction."), stop(8, "Barcelona", "Spain", "A return to the coast.")], false, true),
  makeCruise("bahamas-family-escape", "3-Night Bahamas Family Escape", "royal", "icon", "bahamas", "miami", "2027-07-02", 3, 359, "Ocean", [stop(1, "Miami", "United States", "Let the weekend begin."), stop(2, "Nassau", "Bahamas", "A day of color and calm."), stop(4, "Miami", "United States", "Back before Monday.")], false, true),
  makeCruise("alaska-wild-coast", "14-Night Alaska Wild Coast", "holland", "koningsdam", "alaska", "seattle", "2027-07-18", 14, 1499, "Expedition", [stop(1, "Seattle", "United States", "The wild coast awaits."), stop(4, "Sitka", "Alaska", "Island culture and old growth."), stop(7, "Hubbard Glacier", "Alaska", "A moving wall of blue ice."), stop(10, "Juneau", "Alaska", "Wildlife and waterfalls."), stop(15, "Seattle", "United States", "Return with stories.")], false, true)
];

export function getFeaturedCruises() { return cruises.filter((cruise) => cruise.featured); }
export function getCruiseBySlug(slug: string) { return cruises.find((cruise) => cruise.slug === slug); }
export function getTickerDeals() { return cruises.filter((cruise) => cruise.deal).sort((a, b) => b.savingsPercent - a.savingsPercent); }
